---
name: EnchantedUI
main: ItsRealNise\EnchantedUI\Main
version: "1.0"
api: 5.0.0
load: POSTWORLD
author: ItsRealNise updated by HosseinYT
permissions:
  eshop.command:
    default: true
    description: use all EnchantUI Commands
...
